FROM debian:bookworm-slim

RUN apt update && \
    apt install -y python3-minimal curl lsb-release sudo

RUN curl https://pkg.caida.org/os/debian/bootstrap.sh | bash

RUN apt install -y bgpstream python3-pybgpstream
