FROM debian:buster-slim
LABEL maintainer="Mingwei Zhang <mingwei@caida.org>"

RUN apt update 

RUN apt install -y python2.7-minimal python3.7-minimal curl lsb-release sudo

RUN curl https://pkg.caida.org/os/debian/bootstrap.sh | bash

RUN apt install -y bgpstream=2.1.0 bgpstream2-tools=2.1.0 libbgpstream2-dev=2.1.0 libbgpstream2=2.1.0 python3-pybgpstream=2.0.2
